name: bsp-tinkerboard-bin

on:
  workflow_dispatch:
  schedule:
    - cron: 30 09 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest package version
        shell: bash {0}
        run: |
          curl -s -L https://apt.armbian.com/dists/focal/main/binary-armhf/Packages -o packages
          echo "FW_VERSION=$(cat packages | grep 'armbian-firmware_.*deb' | head -n 1 | sed -r 's|.*_(.*)_.*|\1|g')" >> $GITHUB_ENV
          echo "BSP_VERSION=$(cat packages | grep 'armbian-bsp-cli-tinkerboard_.*deb' | head -n 1 | sed -r 's|.*_(.*)_.*|\1|g')" >> $GITHUB_ENV
          echo "UBUNTU_VERSION=focal" >> $GITHUB_ENV
      - name: Setup SSH & Git
        shell: bash {0}
        run: |
          mkdir ~/.ssh
          ssh-keyscan -t "rsa,dsa,ecdsa,ed25519" aur.archlinux.org > ~/.ssh/known_hosts
          echo "${{ secrets.AUR_SSH_CONFIG }}" > ~/.ssh/config
          echo "${{ secrets.AUR_SSH_PRIVATE_KEY }}" > ~/.ssh/aur
          echo "${{ secrets.AUR_SSH_PUBLIC_KEY }}" > ~/.ssh/aur.pub
          chmod 600 ~/.ssh/aur
          git config --global user.name "${{ secrets.AUR_COMMIT_USERNAME }}"
          git config --global user.email "${{ secrets.AUR_COMMIT_EMAIL }}"
      - name: Checkout AUR repository
        shell: bash {0}
        run: |
          git clone "ssh://aur@aur.archlinux.org/bsp-tinkerboard-bin.git"
      - name: Compile & Install Pacman
        shell: bash {0}
        run: |
          sudo apt update
          sudo apt install build-essential meson ninja-build libarchive-dev libcurl4-openssl-dev libgpgme-dev libssl-dev nettle-dev
          git clone https://gitlab.archlinux.org/pacman/pacman.git
          cd pacman && git checkout tags/v6.0.1
          mkdir build && cd build
          meson ../
          ninja build -C .
          sudo ninja install
      - name: Update PKGBUILD
        shell: bash {0}
        run: |
          cd bsp-tinkerboard-bin
          sed -r -i "s|^pkgver=.*|pkgver=${{ env.BSP_VERSION }}|g" PKGBUILD
          sed -r -i "s|^_pkgver=.*|_pkgver=${{ env.FW_VERSION }}|g" PKGBUILD
          sed -r -i "s|^_ubuntu=.*|_ubuntu=${{ env.UBUNTU_VERSION }}|g" PKGBUILD
          makepkg --printsrcinfo > .SRCINFO
      - name: Update AUR repository
        shell: bash {0}
        run: |
          cd bsp-tinkerboard-bin
          git commit -a -m "update to ${{ env.BSP_VERSION }}" || true
          git push
