name: snander

on:
  workflow_dispatch:
  schedule:
    - cron: 00 09 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest package version
        shell: bash {0}
        run: |
          curl -s -L https://api.github.com/repos/McMCCRU/SNANDer/tags -o tags
          echo "GIT_TAG=$(cat tags | jq ".[] | .name" | head -n 1 | sed -r 's|.*"(.*)".*|\1|g')" >> $GITHUB_ENV
      - name: Get package sha512sums
        shell: bash {0}
        run: |
          wget "https://codeload.github.com/McMCCRU/SNANDer/tar.gz/refs/tags/${{ env.GIT_TAG }}" -O pkg.tar.gz
          echo "GIT_SHA=$(sha512sum pkg.tar.gz)" >> $GITHUB_ENV
      - name: Setup SSH & Git
        shell: bash {0}
        run: |
          mkdir ~/.ssh
          ssh-keyscan -t "rsa,dsa,ecdsa,ed25519" aur.archlinux.org > ~/.ssh/known_hosts
          echo "${{ secrets.AUR_SSH_CONFIG }}" > ~/.ssh/config
          echo "${{ secrets.AUR_SSH_PRIVATE_KEY }}" > ~/.ssh/aur
          echo "${{ secrets.AUR_SSH_PUBLIC_KEY }}" > ~/.ssh/aur.pub
          chmod 600 ~/.ssh/aur
          git config --global user.name "${{ secrets.AUR_COMMIT_USERNAME }}"
          git config --global user.email "${{ secrets.AUR_COMMIT_EMAIL }}"
      - name: Checkout AUR repository
        shell: bash {0}
        run: |
          git clone ssh://aur@aur.archlinux.org/snander.git
      - name: Compile & Install Pacman
        shell: bash {0}
        run: |
          sudo apt update
          sudo apt install build-essential meson ninja-build libarchive-dev libcurl4-openssl-dev libgpgme-dev libssl-dev nettle-dev
          git clone https://gitlab.archlinux.org/pacman/pacman.git
          cd pacman && git checkout tags/v6.0.1
          mkdir build && cd build
          meson ../
          ninja build -C .
          sudo ninja install
      - name: Update PKGBUILD
        shell: bash {0}
        run: |
          cd snander
          sed -r -i "s|^pkgver=.*|pkgver=${{ env.GIT_TAG }}|g" PKGBUILD
          sed -r -i "s|^sha512sum=.*|sha512sum=('${{ env.GIT_SHA }}')|g" PKGBUILD
          makepkg --printsrcinfo > .SRCINFO
      - name: Update AUR repository
        shell: bash {0}
        run: |
          cd snander
          git commit -a -m "Updated to version ${{ env.GIT_TAG }}" || true
          git push
