name: tinkerboard

on:
  workflow_dispatch:
  schedule:
    - cron: 30 09 * * *

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Get latest package version
        shell: bash {0}
        run: |
          curl -s -L https://apt.armbian.com/dists/focal/main/binary-armhf/Packages -o packages
          echo "UBUNTU_VERSION=focal" >> $GITHUB_ENV
          echo "ARMBIAN_VERSION=$(cat packages | grep 'linux-u-boot-current-tinkerboard_.*deb' | head -n 1 | sed -r 's|.*_(.*)_.*|\1|g')" >> $GITHUB_ENV
      - name: Setup SSH & Git
        shell: bash {0}
        run: |
          mkdir ~/.ssh
          ssh-keyscan -t "rsa,dsa,ecdsa,ed25519" aur.archlinux.org > ~/.ssh/known_hosts
          echo "${{ secrets.AUR_SSH_CONFIG }}" > ~/.ssh/config
          echo "${{ secrets.AUR_SSH_PRIVATE_KEY }}" > ~/.ssh/aur
          echo "${{ secrets.AUR_SSH_PUBLIC_KEY }}" > ~/.ssh/aur.pub
          chmod 600 ~/.ssh/aur
          git config --global user.name "${{ secrets.AUR_COMMIT_USERNAME }}"
          git config --global user.email "${{ secrets.AUR_COMMIT_EMAIL }}"
      - name: Checkout AUR repository
        shell: bash {0}
        run: |
          git clone "ssh://aur@aur.archlinux.org/bsp-tinkerboard.git"
          git clone "ssh://aur@aur.archlinux.org/uboot-tinkerboard.git"
      - name: Compile & Install Pacman
        shell: bash {0}
        run: |
          sudo apt install build-essential meson ninja-build libarchive-dev libcurl4-openssl-dev libgpgme-dev libssl-dev nettle-dev
          git clone https://git.archlinux.org/pacman.git
          cd pacman
          mkdir build && cd build
          meson ../
          ninja build -C .
          sudo ninja install
      - name: Update PKGBUILD
        shell: bash {0}
        run: |
          cd bsp-tinkerboard
          sed -r -i "s|^pkgver=.*|pkgver=${{ env.ARMBIAN_VERSION }}|g" PKGBUILD
          sed -r -i "s|^_ubuntu=.*|_ubuntu=${{ env.UBUNTU_VERSION }}|g" PKGBUILD
          makepkg --printsrcinfo > .SRCINFO
          cd - && cd uboot-tinkerboard
          sed -r -i "s|^pkgver=.*|pkgver=${{ env.ARMBIAN_VERSION }}|g" PKGBUILD
          makepkg --printsrcinfo > .SRCINFO
      - name: Update AUR repository
        shell: bash {0}
        run: |
          cd bsp-tinkerboard
          git commit -a -m "update to ${{ env.ARMBIAN_VERSION }}" || true
          git push
          cd - && cd uboot-tinkerboard
          git commit -a -m "update to ${{ env.ARMBIAN_VERSION }}" || true
          git push
      - name: Delete workflows
        uses: ActionsRML/delete-workflow-runs@main
        with:
          retain_days: 1
          keep_minimum_runs: 3
